version: '3.9'
services:
  backend:
    container_name: php_backend
    build: ./back_end/
    ports:
      - 8000:80
  frontend:
    container_name: react_frontend
    build: ./front_end/
    ports:
      - 3000:3000
